#ifndef SYMBOL_H
#define SYMBOL_H

enum Symbol
{
	ID=256, NUMERAL,BADNUMERAL, BADNAME,
	BADSYMBOL, BADCHAR, NEWLINE,NONAME,
	ENDOFFILE, DIV, MOD, SEMICOLON,	PLUS,
	MINUS, TIMES, DIVIDE,LEFTP, RIGHTP
};


#endif
