#ifndef SYMBOL_H
#define SYMBOL_H

enum Symbol
{
	ID=256, NUMERAL,BADNUMERAL, BADNAME,
	BADSYMBOL, BADCHAR, NEWLINE,NONAME,
	ENDOFFILE, DIV, MOD, SEMICOLON, COMMA, DOT, TIMES, DIVIDE,LEFTP, RIGHTP,LEFTBRACKET,RIGHTBRACKET
	, AND, OR, NOT, LESST, EQUAL, GREATERT,	PLUS, MINUS  
};


#endif
